app/routes/dashboard.php
<?php



Route::group([
    'as' => 'dashboard::',
    'prefix' => 'dashboard',
    'namespace' => 'Dashboard',
    'middleware' => ['auth', 'admin'],
], function () {

    /*
    * Dashboard
    */
    Route::get('/', [
        'as' => 'index',
        'uses' => 'MainController@index',
    ]);

    /*
    * Competitions
    */
    Route::resources(['competitions' => 'CompetitionController']);
    Route::post('competitions/{competition}/status/{status}', [
        'as' => 'competitions.status',
        'uses' => 'CompetitionController@changeStatus',
    ]);
    Route::post('competitions/position', [
        'as' => 'competitions.position',
        'uses' => 'CompetitionController@positionUpdate',
    ]);
    Route::post('competitions/tickets/status/live/{ticket}', [
        'as' => 'competitions.ticket.status',
        'uses' => 'CompetitionController@changeTicketStatusToLive',
    ]);

    /**
     * Competition entries
     */
    Route::get('competition-entries', [
       'as' => 'competition-entries.index',
       'uses' => 'CompetitionController@finishedCompetitions'
    ]);
    Route::get('competition-entries/{competition}/find-winner', [
        'as' => 'competition-entries.find-winner',
        'uses' => 'CompetitionController@findWinnerPage',
    ]);
    Route::post('competition-entries/{competition}/find-winner', [
        'as' => 'competition-entries.find-winner',
        'uses' => 'CompetitionController@findWinner',
    ]);
    Route::get('competition-entries/{competition_id?}', [
        'as' => 'competition-entries.table',
        'uses' => 'CompetitionEntriesController@table'
    ]);
    Route::get('competition-entries/export/{competition_id?}', [
        'as' => 'competition-entries.export',
        'uses' => 'CompetitionEntriesController@export'
    ]);


    /*
    * Questions
    */
    Route::resources(['questions' => 'QuestionController'], ['except' => ['show']]);

    /*
    * Promo Codes
    */
    Route::resources(['promo-codes' => 'PromoCodeController'], ['except' => ['show']]);

    /*
    * Past Winners
    */
    Route::resources(['past-winners' => 'PastWinnerController'], ['except' => ['show']]);

    /*
    * Live Draws
    */
    Route::resources(['live-draws' => 'LiveDrawController'], ['except' => ['show']]);

    /*
    * Users
    */
    Route::resources(['users' => 'UserController'], ['except' => ['show']]);
    Route::post('users/change-suspend/{user_id}', 'UserController@changeSuspend')->name('users.suspend');
    /*
    * Results
    */
    Route::resources(['results' => 'ResultController'], ['except' => ['show']]);

    /*
    * Order
    */
    Route::resources(['orders' => 'OrderController'], ['only' => ['show', 'index']]);
    Route::post('orders/{competition}/cancel', [
        'as' => 'orders.cancel',
        'uses' => 'OrderController@cancel',
    ]);

    /*
     * Settings
     */
    Route::group([
        'prefix' => 'settings',
        'as' => 'settings.',
    ], function () {
        Route::get('/', 'SettingsController@edit')->name('edit');
        Route::put('/', 'SettingsController@update')->name('update');
    });

    /**
     * Pages
     */
    Route::group([
        'prefix' => 'pages',
        'as' => 'pages.'
    ], function (){
       Route::resource('page', 'PagesController')->except(['show']);
    });

    /*
     * Statistic
     */
    Route::group([
        'prefix' => 'statistics',
        'as' => 'statistics.',
    ], function () {
        Route::get('/', 'StatisticController@index')->name('index');
    });

    /*
     * Trash
     */
    Route::group([
        'prefix' => 'trash',
        'as' => 'trash.',
    ], function () {
        Route::get('', 'TrashController@index')->name('index');
        Route::post('{competition}/restore', 'TrashController@restoreCompetition')->name('restore-competition');
        Route::delete('{competition}', 'TrashController@destroyCompetition')->name('destroy-competition');
    });

    /*
     * Marketing/SMS
     */
    Route::group([
        'prefix' => 'sms',
        'as' => 'sms.',
    ], function () {
        Route::get('/', 'SmsController@index')->name('index');
        Route::get('/history', 'SmsHistoryController@index')->name('history.index');
        Route::delete('{sms}', 'SmsHistoryController@destroy')->name('destroy');

        Route::get('/create', 'SmsController@create')->name('create');
        Route::post('/store', 'SmsController@store')->name('store');

        // datatables routes
        Route::get('/usersdata', 'SmsController@usersDataSearchData')->name('usersData');
        //create makeQueueFromMessage
        Route::post('/createjob', 'SmsController@makeQueueFromMessage')->name('createjob');
        Route::get('/competitiondata', 'CompetitionController@getCompetitionJson')->name('competitionData');

    });

    /*
     * Marketing
     */
    Route::group([
        'prefix' => 'marketing',
        'as' => 'marketing.',
    ], function () {
//        Route::get('/settings', 'MarketingSettingsController@index')->name('index');
        Route::get('/settings', 'MarketingSettingsController@edit')->name('settings.edit');
        Route::put('/settings', 'MarketingSettingsController@update')->name('settings.update');
    });

    /*
     * Analytics
     */
    Route::group([
        'prefix' => 'analytics',
        'as' => 'analytics.',
    ], function () {
        Route::get('/', 'AnalyticsController@edit')->name('edit');
        Route::put('/', 'AnalyticsController@update')->name('update');
    });
});

app/routes/web.php
<?php

/* Dashboard routes */
include 'dashboard.php';

/**
 * Pages
 */
Route::get('/', [
    'as' => 'main',
    'uses' => 'MainController@main',
]);
Route::post('live-draw/next', [
    'as' => 'live-draw.next',
    'uses' => 'MainController@getNextAvailableLiveDraw',
]);
Route::post('contact', [
    'as' => 'contact.send',
    'uses' => 'MainController@contactForm',
]);
Route::get('live-competitions', [
    'as' => 'live-competitions',
    'uses' => 'MainController@competitions',
]);
Route::get('live-competitions/{slug}', [
    'as' => 'live-competition.show',
    'uses' => 'MainController@competition',
]);
Route::post('live-competitions/{id}/deadline', [
    'as' => 'live-competition.deadline',
    'uses' => 'MainController@checkCompetitionDeadline',
]);
Route::get('winners', [
    'as' => 'winners',
    'uses' => 'MainController@winners',
]);
Route::get('results', [
    'as' => 'results',
    'uses' => 'MainController@results',
]);
Route::get('results/{id?}', [
    'as' => 'result-details',
    'uses' => 'MainController@resultDetails',
]);
Route::get('finished-competitions', [
    'as' => 'finished-competitions',
    'uses' => 'MainController@finishedCompetitions',
]);
Route::get('finished-competition/{slug}', [
    'as' => 'live-competition.finished',
    'uses' => 'MainController@finishedCompetition',
]);
Route::get('page/{slug}', [
    'as' => 'page',
    'uses' => 'MainController@page'
]);

/**
 * User
 */
Route::group([
    'as' => 'user.',
    'prefix' => 'user',
    'middleware' => 'auth',
], function () {
    Route::get('', [
        'as' => 'info',
        'uses' => 'UserController@getMainPage',
    ]);

    Route::post('', [
        'as' => 'update-info',
        'uses' => 'UserController@updateUserInfo',
    ]);

    Route::post('update-password', [
        'as' => 'update-password',
        'uses' => 'UserController@updatePassword',
    ]);
});

/**
 * Static pages
 */
Route::group([
    'as' => 'static.',
], function () {
    Route::view('contacts', 'contacts')->name('contacts');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('terms-conditions', 'terms-conditions')->name('terms-conditions');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('privacy-policy', 'privacy-policy')->name('privacy-policy');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('how-to-play', 'how-to-play')->name('how-to-play');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('charity', 'charity')->name('charity');
});

/**
 * Auth
 */
Route::group([
], function () {
    Auth::routes();
    Route::view('user/login', 'login')->name('user.login')->middleware('guest');
    Route::view('user/register', 'register')->name('user.register')->middleware('guest');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::view('reset-password', 'reset-password')->name('reset-password');
    Route::view('forgot-password', 'forgot-password')->name('forgot-password');
});

/**
 * Cart
 */
Route::group([
    'as' => 'cart.',
    'prefix' => 'cart',
    'middleware' => 'auth',
], function () {
    Route::post('add', 'CartController@addItems')->name('add');
    Route::post('delete/{item_id}', 'CartController@deleteItems')->name('delete');
    Route::post('coupon', 'CartController@checkCouponCode')->name('check-coupon');
    Route::post('random', 'CartController@getRandomTickets')->name('random-tickets');
    Route::post('add-random', 'CartController@addRandomItems')->name('add-random');
    Route::get('data','CartController@getData')->name('data');
});
Route::get('cart', 'CartController@getCartPage')->name('cart.view');

/**
 * Order
 */
Route::group([
    'as' => 'order.',
    'prefix' => 'order',
    'middleware' => 'auth',
], function () {
    Route::post('create', 'OrderController@create')->name('create');
    Route::post('delete/{order}', 'OrderController@delete')->name('delete');
    Route::get('details/{order_id}', 'OrderController@detailsPage')->name('details');
    Route::get('checkout', 'OrderController@checkout')->name('checkout');
    Route::get('payment-result/{order_id}', 'OrderController@paymentResult')->name('payment-result')->where(['order_id' => '[0-9]*']);
});

Route::get('orders','OrderController@index')->name('orders')->middleware('auth');

/**
 * E-commerce
 */
Route::view('times-up', 'times-up')->name('times-up');
Route::match(['get', 'post'],'entries',[
    'middleware' => 'auth',
    'as' => 'entries',
    'uses' => 'MainController@entries'
]);

Route::view('change-password', 'change-password')->name('change-password');

app/resources/views/contacts.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Contact Us</h1>
        </div>
    </div>
</div>

<div class="container margin_60_35">
                <div class="row">
                <!--Grid column-->
                <div class="col-md-6">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <form action="{{route('contact.send')}}" method="POST" class="js_form-contacts">
                                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                                        <h3>Contact Form</h3>
                                        <div class="form-group">
                                            <label>Name</label>
                                            <input type="text" class="form-control" name="name">
                                        </div>
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="email" class="form-control" name="email" required>
                                        </div>
                                        <div class="form-group">
                                            <label>Message</label>
                                            <textarea class="form-control" rows="3" name="message"></textarea>
                                        </div>
                                        <div class="form-group form-check">
                                            <input type="checkbox" class="form-check-input" id="gdpr" name="policy">
                                            <label class="form-check-label" for="gdpr">I consent in submitting my
                                                details inline with your privacy policy.
                                            </label>
                                        </div>
                                        <input type="hidden" name="recaptcha" id="recaptcha">
                                        <button class="btn_1 full-width" type="submit">Submit</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6">
                    <div class="card shadow">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <h3>FAQ</h3>
                                    <div class="faq">
                                        <div class="question">HOW DO I PURCHASE TICKET NUMBERS?</div>
                                        <div class="answer">Playing is easy, first you need to create an account by clicking here. Once you aree logged into your account navigate to the competition you wish to enter, select your numbers or use our lucky dip, answer the question and proceed to checkout.</div>
                                        <div class="question">WHAT HAPPENS IF THE TIMER RUNS OUT AND ALL NUMBERS ARN'T SOLD?</div>
                                        <div class="answer">Dont worry,  we will always hold a draw for each competition,  we will keep draw date extensions to the minimum, See our <a href="{{route('static.terms-conditions')}}">Terms & Conditions</a> for full details.</div>
                                        <div class="question">HOW DO YOU DRAW THE WINNER OF THE COMPETITION?</div>
                                        <div class="answer">We use our specialist random ball machine in order to pick our competition winner. These draws can be watched live via our facebook page.</div>
                                    </div>
                                    <p class="mt-4"><a href="{{route('static.how-to-play')}}">View more FAQ and how to play instructions.</a></p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <!--Grid column-->
            </div>
            <!--Grid row-->

@endsection
@push('after-scripts')
    @include('parts/_recaptcha')
@endpush

app/resources/views/entries.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Account</h1>
        </div>
    </div>
</div>
<div class="container margin_60_35 account_wrap">
    <div class="row">
        <div class="col-md-3 account_menu">
            <h4 class="d-none d-lg-block">Account Menu</h4>
            <nav class="navbar navbar-expand-lg navbar-light p-0">
                <h4 class="d-lg-none">Account Menu</h4>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#accountnav" aria-controls="accountnav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="accountnav">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('entries*')) active @endif" href="{{route('entries')}}"><i class="ti-ticket"></i> Entries</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('orders*')) active @endif" href="{{route('orders')}}"><i class="ti-shopping-cart"></i> Orders</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('user.info*')) active @endif" href="{{route('user.info')}}"><i class="ti-user"></i> Account Details</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link @if(request()->is('change-password*')) active @endif" href="{{route('change-password')}}"><i class="ti-lock"></i> Change Password</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="{{route('logout')}}"><i class="ti-power-off"></i> Log Out</a>
                        </li>
                        @auth
                            @if(Auth::user() && Auth::user()->isAdmin())
                        <li class="nav-item">
                        <a class="nav-link" href="{{route('dashboard::index')}}"><i class="ti-key"></i> Admin Dashboard</a>
                        </li>
                            @endif
                        @endauth
                    </ul>
                </div>
            </nav>
        </div>
        <div class="col-md-8 order_wrap mt-4">
            <h2>Entries</h2>
            <div class="card mb-3">
                <div class="card-body">
                    <div class="js_tbl-wrap" data-method="POST" data-action="{{url()->current()}}">
                        @include('parts/_entries-table', ['entries' => $entries])
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

app/resources/views/finished-competition.blade.php
@extends('core.base')

@section('content')



<div class="container margin_60">
    <div class="row align-items-center">
        <div class="col-md-6">
        <img src="{{$competition->present()->main_image}}" alt="{{$competition->title}}" style="width:100%" />
        </div>
        <div class="col-md-6">
            <div class="comp_info">
                <h1>{{$competition->title}}</h1>
              <div class="finished-details mt-4">  
                <h3>Competition Closed : <span>{{date('d/m/Y \@ H:i', strtotime($competition->deadline))}}</span></h3>
                @if($competition->winner_name || $competition->winner_number)
                <h3>Competition Winner: <span>{{$competition->winner_name}}</span></h3>
                <h3>Winning Ticket Number : <span>{{$competition->winner_number}}</span></h3>
                @endif
              </div>
            </div>
          <div>
            <!-- /prod_info -->
        </div>
    </div>
    <!-- /row -->

</div>
<!-- /container -->
<div class="enter-competition mt-4">
    <div class="container">
        <div class="main_title">
            <h2>Competition Entries</h2>
        </div>
        <div class="row">
            <div class="col-md-12 add_bottom_25">
                <table id="entry-table" class="table table-striped">
                    <thead>
                        <tr>
                            <th>Username</th>
                            <th>Ticket Number</th>
                            <th>Purchased</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($competition->tickets as $ticket)
                        <tr>
                            <td>{{$ticket->user->username}}</td>
                            <td>{{$ticket->number}}</td>
                            <td>{{date('jS F Y \@ H:i a', strtotime($ticket->created_at))}}</td>
                        </tr>
                        @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>Username</th>
                            <th>Ticket Number</th>
                            <th>Purchased</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection

@push('after-scripts')
    <script src="{{asset('js/datatables.min.js')}}"></script>
    <script src="{{asset('js/dataTables.bootstrap4.min.js')}}"></script>
    <script src="{{asset('js/dataTables.fixedHeader.min.js')}}"></script>
    <script src="{{asset('js/dataTables.responsive.min.js')}}"></script>
@endpush

app/resources/views/forgot-password.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Forgot Password</h1>
        </div>
    </div>
</div>
<!-- /top_banner -->
<div class="container margin_30">
    <!-- /page_header -->
    <div class="row">
        <div class="col-xl-6 col-lg-6 col-md-8 offset-md-3">
            <div class="box_account">
                <div class="form_container">
                    <h2>Reset Password</h2>
                    <form action="{{route('password.email')}}" method="post" class="js_form-forgot-password">
                    <input type="hidden" name="_token" value="{{csrf_token()}}">
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" class="form-control" placeholder="Email Address" name="email" required="required">
                    </div>
                    <div class="text-center"><button type="submit" class="btn_1 full-width">Reset Password</button></div>
                    </form>
                </div>
                <!-- /form_container -->
                <p class="float-right pt-2">No account yet? <a href="{{route('user.register')}}">Create one here.</a></p>
            </div>
            <!-- /box_account -->
        </div>
    </div>
</div>
<!-- /container -->

@endsection

app/resources/views/live-competitions.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Live Competitions</h1>
        </div>
    </div>
</div>

<div class="container margin_60_35 competition-grid">
    <div class="row small-gutters">
        @foreach($competitions as $competition)
            @include('parts/_competition-card')
        @endforeach
    </div>
    <!-- /row -->
    @include('parts/_pagination', ['paginator' => $competitions])
</div>

@endsection

app/resources/views/order-details.blade.php
@extends('core.base')

@section('content')

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Order Details</h1>
        </div>
    </div>
</div>
<!-- /top_banner -->
<div class="container margin_30">
    <div class="row order_wrap">
        <div class="col-md-12">
            <div class="card shadow mb-3">
                @include('orders.parts._order-items-details', ['order' => $order])
            </div>
        </div>
        <div class="col-lg-12">
            <!-- Card -->
            <div class="card mb-3 shadow">
                  @include('orders.parts._order-details', [ 'order' => $order, 'btnLink' => route('user.info') ])
            <!-- Card -->
        </div>
    </div>
</div>

@endsection

app/resources/views/order-status.blade.php
@extends('core.base')

@section('content')

    @if($status === 'success')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <div id="confirm">
                    <div class="icon icon--order-success svg add_bottom_15">
                        <svg xmlns="http://www.w3.org/2000/svg" width="72" height="72">
                            <g fill="none" stroke="#8EC343" stroke-width="2">
                                <circle cx="36" cy="36" r="35" style="stroke-dasharray:240px, 240px; stroke-dashoffset: 480px;"></circle>
                                <path d="M17.417,37.778l9.93,9.909l25.444-25.393" style="stroke-dasharray:50px, 50px; stroke-dashoffset: 0px;"></path>
                            </g>
                        </svg>
                    </div>
                <h2>Order Successful!</h2>
                <p>A confirmational email is on it's way to you. You can find details about your order below or inside your account.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <a href="{{route('order.details', $order->id)}}" class="btn_1 full-width">View Order Details</a>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
    @else
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-5">
                <div id="confirm" class="add_top_60 add_bottom_60">
                    <div class="icon icon--order-success svg add_bottom_15">
                        <svg  xmlns="http://www.w3.org/2000/svg" width="72" height="72">
                            <g fill="none" stroke="#E20707" stroke-width="2">
                                <circle cx="36" cy="36" r="35" style="stroke-dasharray:240px, 240px; stroke-dashoffset: 480px;"></circle>
                                <path d="M23.6,47.7l25.4-25.4" style="stroke-dasharray:50px, 50px; stroke-dashoffset: 0px;" />
                                <path d="M23.8,22.3l25.4,25.4" style="stroke-dasharray:50px, 50px; stroke-dashoffset: 0px;" />
                            </g>
                        </svg>
                    </div>
                <h2>Order Unsuccessful!</h2>
                <p>Unfortunately, we could not process this order. This could be due to several different reasons, please try again and reconfirm your payment details.</p>
                <a href="{{url('/live-competitions')}}" class="btn_1">View Live Competitions</a>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
    @endif
@endsection

app/resources/views/page.blade.php
@extends('core.base')

@section('content')
<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center" data-opacity-mask="rgba(0, 0, 0, 0.3)">
        <div class="container">
            <h1>{{$page->title}}</h1>
        </div>
    </div>
</div>
<!-- /top_banner -->
<div class="container margin_60_35 account_wrap">
    <div class="row">
        {!! $page->content !!}
    </div>
</div>
@endsection

app/resources/views/payment-result.blade.php
@extends('core.base')

@section('content')

@if(isset($order))
    @if($order->isSuccessful())
        <div class="container margin_60_35">
            <div class="row justify-content-center text-center">
                <div class="col-md-5">
                    <div id="confirm">
                        <div class="icon icon--order-success svg add_bottom_15">
                            <svg xmlns="http://www.w3.org/2000/svg" width="72" height="72">
                                <g fill="none" stroke="#8EC343" stroke-width="2">
                                    <circle cx="36" cy="36" r="35" style="stroke-dasharray:240px, 240px; stroke-dashoffset: 480px;"></circle>
                                    <path d="M17.417,37.778l9.93,9.909l25.444-25.393" style="stroke-dasharray:50px, 50px; stroke-dashoffset: 0px;"></path>
                                </g>
                            </svg>
                        </div>
                    <h2>Order Successful!</h2>
                    <p>A confirmational email is on it's way to you. You can find details about your order below or inside your account.</p>
                    </div>
                </div>
            </div>
            <!-- /row -->
            <div class="row order_wrap">
                <div class="col-md-12">
                    <div class="card shadow mb-3">
                        @include('orders.parts._order-items-details', ['order' => $order])
                    </div>
                </div>
                <div class="col-lg-12">
                    <!-- Card -->
                    <div class="card mb-3 shadow">
                    @include('orders.parts._order-details', ['order' => $order, 'btnLink' => route('order.details', $order->id)])
                    </div>
                    <!-- Card -->
                </div>
            </div>
        </div>
        <!-- /container -->
        @push('before-scripts')
        <script>
            window.dataLayer = window.dataLayer || [];
            dataLayer.push(@json($order->present()->googleTagManagerStructure));
        </script>
        @endpush 
    @else
        <div class="container margin_60_35">
            <div class="row justify-content-center text-center">
                <div class="col-md-5">
                    <div id="confirm" class="add_top_60 add_bottom_60">
                        <div class="icon icon--order-success svg add_bottom_15">
                            <svg  xmlns="http://www.w3.org/2000/svg" width="72" height="72">
                                <g fill="none" stroke="#E20707" stroke-width="2">
                                    <circle cx="36" cy="36" r="35" style="stroke-dasharray:240px, 240px; stroke-dashoffset: 480px;"></circle>
                                    <path d="M23.6,47.7l25.4-25.4" style="stroke-dasharray:50px, 50px; stroke-dashoffset: 0px;" />
                                    <path d="M23.8,22.3l25.4,25.4" style="stroke-dasharray:50px, 50px; stroke-dashoffset: 0px;" />
                                </g>
                            </svg>
                        </div>
                    <h2>Order Unsuccessful!</h2>
                    <p>Unfortunately, we could not process this order. This could be due to several different reasons, please try again and reconfirm your payment details.</p>
                    <a href="{{route('live-competitions')}}" class="btn_1">View Live Competitions</a>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    @endif
    @else
        <div class="container margin_60_35">
            <div class="row justify-content-center">
                <div class="col-md-12">
                    <div class="add_top_60 add_bottom_60">
                    <h2>Your basket is empty!</h2>
                    <a href="{{route('live-competitions')}}" class="btn_1">View Live Competitions</a>
                    </div>
                </div>
            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    @endif
@endsection