app/routes/dashboard.php
<?php



Route::group([
    'as' => 'dashboard::',
    'prefix' => 'dashboard',
    'namespace' => 'Dashboard',
    'middleware' => ['auth', 'admin'],
], function () {

    /*
    * Dashboard
    */
    Route::get('/', [
        'as' => 'index',
        'uses' => 'MainController@index',
    ]);

    /*
    * Competitions
    */
    Route::resources(['competitions' => 'CompetitionController']);
    Route::post('competitions/{competition}/status/{status}', [
        'as' => 'competitions.status',
        'uses' => 'CompetitionController@changeStatus',
    ]);
    Route::post('competitions/position', [
        'as' => 'competitions.position',
        'uses' => 'CompetitionController@positionUpdate',
    ]);
    Route::post('competitions/tickets/status/live/{ticket}', [
        'as' => 'competitions.ticket.status',
        'uses' => 'CompetitionController@changeTicketStatusToLive',
    ]);

    /**
     * Competition entries
     */
    Route::get('competition-entries', [
       'as' => 'competition-entries.index',
       'uses' => 'CompetitionController@finishedCompetitions'
    ]);
    Route::get('competition-entries/{competition}/find-winner', [
        'as' => 'competition-entries.find-winner',
        'uses' => 'CompetitionController@findWinnerPage',
    ]);
    Route::post('competition-entries/{competition}/find-winner', [
        'as' => 'competition-entries.find-winner',
        'uses' => 'CompetitionController@findWinner',
    ]);
    Route::get('competition-entries/{competition_id?}', [
        'as' => 'competition-entries.table',
        'uses' => 'CompetitionEntriesController@table'
    ]);
    Route::get('competition-entries/export/{competition_id?}', [
        'as' => 'competition-entries.export',
        'uses' => 'CompetitionEntriesController@export'
    ]);


    /*
    * Questions
    */
    Route::resources(['questions' => 'QuestionController'], ['except' => ['show']]);

    /*
    * Promo Codes
    */
    Route::resources(['promo-codes' => 'PromoCodeController'], ['except' => ['show']]);

    /*
    * Past Winners
    */
    Route::resources(['past-winners' => 'PastWinnerController'], ['except' => ['show']]);

    /*
    * Live Draws
    */
    Route::resources(['live-draws' => 'LiveDrawController'], ['except' => ['show']]);

    /*
    * Users
    */
    Route::resources(['users' => 'UserController'], ['except' => ['show']]);
    Route::post('users/change-suspend/{user_id}', 'UserController@changeSuspend')->name('users.suspend');
    /*
    * Results
    */
    Route::resources(['results' => 'ResultController'], ['except' => ['show']]);

    /*
    * Order
    */
    Route::resources(['orders' => 'OrderController'], ['only' => ['show', 'index']]);
    Route::post('orders/{competition}/cancel', [
        'as' => 'orders.cancel',
        'uses' => 'OrderController@cancel',
    ]);

    /*
     * Settings
     */
    Route::group([
        'prefix' => 'settings',
        'as' => 'settings.',
    ], function () {
        Route::get('/', 'SettingsController@edit')->name('edit');
        Route::put('/', 'SettingsController@update')->name('update');
    });

    /**
     * Pages
     */
    Route::group([
        'prefix' => 'pages',
        'as' => 'pages.'
    ], function (){
       Route::resource('page', 'PagesController')->except(['show']);
    });

    /*
     * Statistic
     */
    Route::group([
        'prefix' => 'statistics',
        'as' => 'statistics.',
    ], function () {
        Route::get('/', 'StatisticController@index')->name('index');
    });

    /*
     * Trash
     */
    Route::group([
        'prefix' => 'trash',
        'as' => 'trash.',
    ], function () {
        Route::get('', 'TrashController@index')->name('index');
        Route::post('{competition}/restore', 'TrashController@restoreCompetition')->name('restore-competition');
        Route::delete('{competition}', 'TrashController@destroyCompetition')->name('destroy-competition');
    });

    /*
     * Marketing/SMS
     */
    Route::group([
        'prefix' => 'sms',
        'as' => 'sms.',
    ], function () {
        Route::get('/', 'SmsController@index')->name('index');
        Route::get('/history', 'SmsHistoryController@index')->name('history.index');
        Route::delete('{sms}', 'SmsHistoryController@destroy')->name('destroy');

        Route::get('/create', 'SmsController@create')->name('create');
        Route::post('/store', 'SmsController@store')->name('store');

        // datatables routes
        Route::get('/usersdata', 'SmsController@usersDataSearchData')->name('usersData');
        //create makeQueueFromMessage
        Route::post('/createjob', 'SmsController@makeQueueFromMessage')->name('createjob');
        Route::get('/competitiondata', 'CompetitionController@getCompetitionJson')->name('competitionData');

    });

    /*
     * Marketing
     */
    Route::group([
        'prefix' => 'marketing',
        'as' => 'marketing.',
    ], function () {
//        Route::get('/settings', 'MarketingSettingsController@index')->name('index');
        Route::get('/settings', 'MarketingSettingsController@edit')->name('settings.edit');
        Route::put('/settings', 'MarketingSettingsController@update')->name('settings.update');
    });

    /*
     * Analytics
     */
    Route::group([
        'prefix' => 'analytics',
        'as' => 'analytics.',
    ], function () {
        Route::get('/', 'AnalyticsController@edit')->name('edit');
        Route::put('/', 'AnalyticsController@update')->name('update');
    });
});

app/routes/web.php
<?php

/* Dashboard routes */
include 'dashboard.php';

/**
 * Pages
 */
Route::get('/', [
    'as' => 'main',
    'uses' => 'MainController@main',
]);
Route::post('live-draw/next', [
    'as' => 'live-draw.next',
    'uses' => 'MainController@getNextAvailableLiveDraw',
]);
Route::post('contact', [
    'as' => 'contact.send',
    'uses' => 'MainController@contactForm',
]);
Route::get('live-competitions', [
    'as' => 'live-competitions',
    'uses' => 'MainController@competitions',
]);
Route::get('live-competitions/{slug}', [
    'as' => 'live-competition.show',
    'uses' => 'MainController@competition',
]);
Route::post('live-competitions/{id}/deadline', [
    'as' => 'live-competition.deadline',
    'uses' => 'MainController@checkCompetitionDeadline',
]);
Route::get('winners', [
    'as' => 'winners',
    'uses' => 'MainController@winners',
]);
Route::get('results', [
    'as' => 'results',
    'uses' => 'MainController@results',
]);
Route::get('results/{id?}', [
    'as' => 'result-details',
    'uses' => 'MainController@resultDetails',
]);
Route::get('finished-competitions', [
    'as' => 'finished-competitions',
    'uses' => 'MainController@finishedCompetitions',
]);
Route::get('finished-competition/{slug}', [
    'as' => 'live-competition.finished',
    'uses' => 'MainController@finishedCompetition',
]);
Route::get('page/{slug}', [
    'as' => 'page',
    'uses' => 'MainController@page'
]);

/**
 * User
 */
Route::group([
    'as' => 'user.',
    'prefix' => 'user',
    'middleware' => 'auth',
], function () {
    Route::get('', [
        'as' => 'info',
        'uses' => 'UserController@getMainPage',
    ]);

    Route::post('', [
        'as' => 'update-info',
        'uses' => 'UserController@updateUserInfo',
    ]);

    Route::post('update-password', [
        'as' => 'update-password',
        'uses' => 'UserController@updatePassword',
    ]);
});

/**
 * Static pages
 */
Route::group([
    'as' => 'static.',
], function () {
    Route::view('contacts', 'contacts')->name('contacts');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('terms-conditions', 'terms-conditions')->name('terms-conditions');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('privacy-policy', 'privacy-policy')->name('privacy-policy');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('how-to-play', 'how-to-play')->name('how-to-play');
});

Route::group([
    'as' => 'static.',
], function () {
    Route::view('charity', 'charity')->name('charity');
});

/**
 * Auth
 */
Route::group([
], function () {
    Auth::routes();
    Route::view('user/login', 'login')->name('user.login')->middleware('guest');
    Route::view('user/register', 'register')->name('user.register')->middleware('guest');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout');
    Route::view('reset-password', 'reset-password')->name('reset-password');
    Route::view('forgot-password', 'forgot-password')->name('forgot-password');
});

/**
 * Cart
 */
Route::group([
    'as' => 'cart.',
    'prefix' => 'cart',
    'middleware' => 'auth',
], function () {
    Route::post('add', 'CartController@addItems')->name('add');
    Route::post('delete/{item_id}', 'CartController@deleteItems')->name('delete');
    Route::post('coupon', 'CartController@checkCouponCode')->name('check-coupon');
    Route::post('random', 'CartController@getRandomTickets')->name('random-tickets');
    Route::post('add-random', 'CartController@addRandomItems')->name('add-random');
    Route::get('data','CartController@getData')->name('data');
});
Route::get('cart', 'CartController@getCartPage')->name('cart.view');

/**
 * Order
 */
Route::group([
    'as' => 'order.',
    'prefix' => 'order',
    'middleware' => 'auth',
], function () {
    Route::post('create', 'OrderController@create')->name('create');
    Route::post('delete/{order}', 'OrderController@delete')->name('delete');
    Route::get('details/{order_id}', 'OrderController@detailsPage')->name('details');
    Route::get('checkout', 'OrderController@checkout')->name('checkout');
    Route::get('payment-result/{order_id}', 'OrderController@paymentResult')->name('payment-result')->where(['order_id' => '[0-9]*']);
});

Route::get('orders','OrderController@index')->name('orders')->middleware('auth');

/**
 * E-commerce
 */
Route::view('times-up', 'times-up')->name('times-up');
Route::match(['get', 'post'],'entries',[
    'middleware' => 'auth',
    'as' => 'entries',
    'uses' => 'MainController@entries'
]);

Route::view('change-password', 'change-password')->name('change-password');

app/resources/views/payment/trust-payment/checkout.blade.php
@extends('core.base')

@section('content')
{{--  Add TrastPayment library  --}}
<script src="{{$jsLibUrl}}"></script>

<div class="top_banner">
    <div class="opacity-mask d-flex align-items-center">
        <div class="container">
            <h1>Checkout</h1>
        </div>
    </div>
</div>
<div class="content_wrap basket js_trust-payment">
    <div class="container margin_60_35">
        @if($cart->getContent()->count())
            <div class="row">
                <div class="col-lg-8 offset-md-2">
                    @if($cart->getTotal() > 0)
                        {{-- New payment method --}}
                        <div class="payment-method">
                            <div class="pay-top sin-payment">
                                <input id="payment_method_1" class="input-radio" type="radio" value="cheque"
                                       checked="checked" name="payment_method">
                                <label for="payment_method_1"> Credit / Debit Card </label>
                            </div>
                        </div>
                        <div class="card shadow mb-3">
                            <div class="card-body payment-form">
                                <div id="st-notification-frame"></div>
                                <form id="st-form" action="{{route('trust-payment.result')}}" data-cart="{{route('cart.data')}}" method="POST">
                                    {!! csrf_field() !!}

                                    @if(!$useSavedCard)
                                        <div id="st-card-number" class="st-card-number"></div>
                                        <div id="st-expiration-date" class="st-expiration-date"></div>
                                    @endif

                                    <div id="st-security-code" class="st-security-code"></div>
                                    <input id="order" type="hidden" name="order_id">
                                    <input type="hidden" name="user_id" value="{{$user->id}}">
                                    <input id="save-payment-method" type="hidden" name="save_payment_method">
                                    <div class="form-check mt-2 mb-2">
                                        <input class="form-check-input js_store-card" name="store-cards" type="checkbox"
                                               id="store-cards" @if(!$useSavedCard) @else checked @endif>
                                        <label class="form-check-label" for="store-cards">
                                            <strong>Store these card details for future purchases.</strong>
                                        </label>
                                    </div>
                                    <button type="submit" id="st-form__submit" class="st-form__submit"
                                            >Pay
                                    </button>
                                </form>
                                <script>
                                    var st = SecureTrading({
                                        jwt: @json($jwtToken),
                                        panIcon: true,
                                        submitOnSuccess: false,
                                        submitOnError: false,
                                        disableNotification: true,
                                        submitCallback: function (data){
                                            app.trustPaymentProcessor.processOrderForm();
                                        },
                                        @if($useSavedCard)
                                        fieldsToSubmit: ['securitycode'],
                                        @endif

                                        livestatus: @json($livePaymentStatus),
                                        styles: {
                                            'font-size-input': '16px',
                                            'color-input': '#495057',
                                            'background-color-input': '#fff',
                                            'border-color-input': '#ced4da',
                                            'border-size-input': '1px',
                                            'border-radius-input': '5px',
                                            'line-height-input': '1.5',
                                            'color-label': '#000',
                                            'font-size-label': '17px',
                                            'line-height-label': '1.7',
                                        }
                                    });
                                    function initTrustPayment() {
                                        st.Components();
                                    }
                                </script>
                            </div>
                        </div>
                    @endif
                </div>
            </div>
            <div class="row basket_wrap">
                <div class="col-lg-8 offset-md-2">
                    <div class="card mb-3 shadow">
                        <form action="{{$orderCreatingUrl}}" method="{{$orderCreatingMethod}}"
                              @if($cart->getTotal() > 0) class="js_order-form" @endif>
                            {!! csrf_field() !!}
                            <div class="card-body">
                                <h5>Basket Total</h5>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                                        Entries <span>£{{ $cart->getSubTotal() }}</span></li>
                                    @if($cart->getDiscount()->isNotEmpty())
                                        <li class="list-group-item d-flex justify-content-between align-items-center px-0">
                                            Coupon Code <span>- £{{$cart->getDiscountValue()}}</span></li>
                                    @endif
                                    <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                                        <div><strong>Total</strong></div>
                                        <span><strong>£{{$cart->getTotal()}}</strong></span>
                                    </li>
                                </ul>
                                <div class="form-check mt-2 mb-2" style="display: none;">
                                    <input class="form-check-input" name="agree" type="checkbox" id="checkbox-agree"
                                           checked  required>
                                </div>
                                @if($cart->getTotal() == 0)
                                    <button type="submit" class="btn_1 full-width">Checkout
                                    </button>
                                @endif
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        @else
            <h4>Your cart is empty</h4>
        @endif
        @if(!app()->environment('local'))
            @include('parts/_body-checkout')
        @endif
    </div>
</div>
@endsection